export const TURKEY_PROVINCES = [
  "Adana",
  "Adıyaman",
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkari",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce"
] as const;

export const DISTRICTS_BY_PROVINCE: Record<string, string[]> = {
  Adana: ["Seyhan", "Çukurova", "Yüreğir", "Sarıçam", "Ceyhan"],
  Adıyaman: ["Merkez", "Kahta", "Besni", "Gölbaşı"],
  Afyonkarahisar: ["Merkez", "Sandıklı", "Dinar", "Bolvadin"],
  Ağrı: ["Merkez", "Doğubayazıt", "Patnos", "Diyadin"],
  Amasya: ["Merkez", "Merzifon", "Suluova", "Taşova"],
  Ankara: ["Çankaya", "Keçiören", "Yenimahalle", "Etimesgut", "Gölbaşı", "Sincan"],
  Antalya: ["Muratpaşa", "Kepez", "Konyaaltı", "Alanya", "Manavgat", "Serik"],
  Artvin: ["Merkez", "Hopa", "Borçka", "Arhavi"],
  Aydın: ["Efeler", "Kuşadası", "Nazilli", "Didim", "Söke"],
  Balıkesir: ["Karesi", "Altıeylül", "Ayvalık", "Bandırma", "Edremit"],
  Bilecik: ["Merkez", "Bozüyük", "Osmaneli"],
  Bingöl: ["Merkez", "Genç", "Solhan"],
  Bitlis: ["Merkez", "Tatvan", "Ahlat"],
  Bolu: ["Merkez", "Gerede", "Mudurnu"],
  Burdur: ["Merkez", "Bucak", "Gölhisar"],
  Bursa: ["Osmangazi", "Nilüfer", "Yıldırım", "İnegöl", "Mudanya"],
  "Çanakkale": ["Merkez", "Biga", "Çan", "Gelibolu"],
  Çankırı: ["Merkez", "Çerkeş", "Ilgaz"],
  Çorum: ["Merkez", "Sungurlu", "Osmancık"],
  Denizli: ["Pamukkale", "Merkezefendi", "Çivril", "Acıpayam"],
  Diyarbakır: ["Kayapınar", "Bağlar", "Sur", "Yenişehir", "Bismil"],
  Edirne: ["Merkez", "Keşan", "Uzunköprü"],
  Elazığ: ["Merkez", "Kovancılar", "Karakoçan"],
  Erzincan: ["Merkez", "Tercan", "Refahiye"],
  Erzurum: ["Yakutiye", "Palandöken", "Aziziye", "Oltu"],
  Eskişehir: ["Odunpazarı", "Tepebaşı", "Sivrihisar"],
  Gaziantep: ["Şahinbey", "Şehitkamil", "Nizip", "İslahiye"],
  Giresun: ["Merkez", "Bulancak", "Espiye"],
  "Gümüşhane": ["Merkez", "Kelkit", "Torul"],
  Hakkari: ["Merkez", "Yüksekova", "Şemdinli"],
  Hatay: ["Antakya", "İskenderun", "Defne", "Dörtyol", "Samandağ"],
  Isparta: ["Merkez", "Yalvaç", "Eğirdir"],
  Mersin: ["Yenişehir", "Mezitli", "Toroslar", "Erdemli", "Tarsus"],
  İstanbul: ["Beşiktaş", "Kadıköy", "Şişli", "Sarıyer", "Üsküdar", "Başakşehir", "Beylikdüzü"],
  İzmir: ["Konak", "Karşıyaka", "Bornova", "Buca", "Çeşme", "Torbalı"],
  Kars: ["Merkez", "Kağızman", "Sarıkamış"],
  Kastamonu: ["Merkez", "Tosya", "Taşköprü"],
  Kayseri: ["Melikgazi", "Kocasinan", "Talas", "Develi"],
  Kırklareli: ["Merkez", "Lüleburgaz", "Babaeski"],
  Kırşehir: ["Merkez", "Mucur", "Kaman"],
  Kocaeli: ["İzmit", "Gebze", "Başiskele", "Kartepe", "Darıca"],
  Konya: ["Selçuklu", "Meram", "Karatay", "Ereğli"],
  Kütahya: ["Merkez", "Tavşanlı", "Simav"],
  Malatya: ["Battalgazi", "Yeşilyurt", "Akçadağ"],
  Manisa: ["Şehzadeler", "Yunusemre", "Akhisar", "Salihli", "Turgutlu"],
  "Kahramanmaraş": ["Dulkadiroğlu", "Onikişubat", "Elbistan"],
  Mardin: ["Artuklu", "Kızıltepe", "Midyat"],
  Muğla: ["Bodrum", "Fethiye", "Marmaris", "Milas", "Menteşe"],
  Muş: ["Merkez", "Bulanık", "Malazgirt"],
  Nevşehir: ["Merkez", "Ürgüp", "Avanos"],
  Niğde: ["Merkez", "Bor", "Ulukışla"],
  Ordu: ["Altınordu", "Ünye", "Fatsa"],
  Rize: ["Merkez", "Çayeli", "Ardeşen"],
  Sakarya: ["Adapazarı", "Serdivan", "Akyazı", "Sapanca"],
  Samsun: ["Atakum", "İlkadım", "Canik", "Bafra"],
  Siirt: ["Merkez", "Kurtalan", "Eruh"],
  Sinop: ["Merkez", "Boyabat", "Gerze"],
  Sivas: ["Merkez", "Şarkışla", "Suşehri"],
  Tekirdağ: ["Süleymanpaşa", "Çorlu", "Çerkezköy", "Marmaraereğlisi"],
  Tokat: ["Merkez", "Erbaa", "Turhal"],
  Trabzon: ["Ortahisar", "Akçaabat", "Yomra"],
  Tunceli: ["Merkez", "Pertek", "Mazgirt"],
  "Şanlıurfa": ["Eyyübiye", "Haliliye", "Karaköprü", "Siverek"],
  Uşak: ["Merkez", "Banaz", "Eşme"],
  Van: ["İpekyolu", "Edremit", "Tuşba", "Erciş"],
  Yozgat: ["Merkez", "Sorgun", "Boğazlıyan"],
  Zonguldak: ["Merkez", "Ereğli", "Çaycuma"],
  Aksaray: ["Merkez", "Ortaköy", "Eskil"],
  Bayburt: ["Merkez", "Demirözü", "Aydıntepe"],
  Karaman: ["Merkez", "Ermenek", "Sarıveliler"],
  Kırıkkale: ["Merkez", "Yahşihan", "Keskin"],
  Batman: ["Merkez", "Kozluk", "Gercüş"],
  "Şırnak": ["Merkez", "Cizre", "Silopi"],
  Bartın: ["Merkez", "Amasra", "Ulus"],
  Ardahan: ["Merkez", "Göle", "Çıldır"],
  Iğdır: ["Merkez", "Tuzluca", "Aralık"],
  Yalova: ["Merkez", "Çiftlikköy", "Çınarcık"],
  Karabük: ["Merkez", "Safranbolu", "Eskipazar"],
  Kilis: ["Merkez", "Elbeyli", "Musabeyli"],
  Osmaniye: ["Merkez", "Kadirli", "Düziçi"],
  Düzce: ["Merkez", "Akçakoca", "Cumayeri"]
};
